name: Build and Deploy FrontEnd

on:
  push:
    branches:
      - main

jobs:
  
  portainer-deploy:
    #needs: dockerhub-push
    runs-on: ubuntu-latest
    steps:      
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14' # Escolha a versão do Node.js que você precisa

      - name: Install dependencies
        run: npm install axios https dotenv

      - name: Run Portainer deploy script
        run: node ./portainer-deploy-script.js
        env:
          USERNAME: ${{ secrets.PORTAINER_URL }}
          PASSWORD: ${{ secrets.PORTAINER_USER }}
          DOCKER_AUTH: ${{ secrets.PORTAINER_PWD }}
          PORTAINER_URL: ${{ secrets.PORTAINER_STACK_NAME }}
          NOME_IMAGEM: ${{ secrets.PORTAINER_STACK_FILE }}







        
