name: Build and Deploy FrontEnd

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v4
    
    - name: Login into docker
      uses: docker/login-action@v3.2.0
      with:
        username: ${{secrets.DOCKERHUB_USER}}
        password: ${{secrets.DOCKERHUB_PWD}}

    - name: Set up Docker Build and Push latest
      uses: docker/build-push-action@v5.3.0
      with:
        push: true
        tags:
          copapel/funil_vendas_frontend:latest
    
    - name: Set up Docker Build and Push version
      uses: docker/build-push-action@v5.3.0
      with:
        push: true
        tags:
          copapel/funil_vendas_frontend:${{ github.RUN_NUMBER }}
  
  #portainer-deploy:
  # runs-on: ubuntu-latest


    
    #steps:
     # - name: Check out repo
      #  uses: actions/checkout@v4
      #
      #- name: Deploy to Portainer
      #  run:
      #    curl -X GET https://167.114.128.102:9443/api/auth








        
